### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by nhughart** [PayFabric/Magento-Plugin#1]
Would it be possible to reorganize the repository structure such that the module files are at the root of the repository?  Currently it is difficult to install your module via composer due to the composer.json not being at the root of the repository.  Alternatively getting the module into the packagist.org repository would further simplify the process.

In addition to the above, the composer.json could use a few adjustments to the dependencies:
- The magento/magento-composer-installer version constraint should be '*'
- All other version constraints should be >=100 to allow installation on various versions.  These could be more explicitly defined as well if specific versions have been tested.

**Comment by pmsteil** [comment]
Agree here.  This is the best practice for Magento plugins.  Installing it via app/code is not the correct way to install on Magento, using Composer is best because it makes it super easy to upgrade at any time you tag a new version in the repo.

**Comment by JackZhang-nodus** [comment]
Thank you for your comment. Composer installation will be supported in the next version soon.
