### ISSUE TITLE
Unable to authorize a card through PayFabric when creating an order in the admin panel

### ISSUE THREAD

**Issue by navarr** [PayFabric/Magento-Plugin#10]
💻  **Pre-Requisites**

* Magento Open-Source 2.4.5-p1
* PayFabric 2.0.0

❔ **Recreation Steps**

1. Log in to the Magento Backend
2. Go to Sales > Orders
3. Click "Create New Order"
4. Choose an existing customer or create a new customer (same result)
5. Fill out order details including products
6. Under "Payment Method" click the PayFabric payment method

✔️ **Expected Results**

* PayFabric iframe appears (and includes the card history of the customer attached to the order if choosing an existing customer)

❌  **Actual Results**

* No IFrame appears.  Order can be placed with no credit card details.

**Comment by JAllison4u** [comment]
We have received your submission and have reviewed it internally. 
There are restrictions in the Magneto support for hosted payments on the Admin panel.
