### ISSUE TITLE
Can the Magento Plugin auto-capture?

### ISSUE THREAD

**Issue by pmsteil** [PayFabric/Magento-Plugin#2]
Hello,

We are considering moving to your payment gateway for Magento CC processing.

The readme seems to indicate that one would have to login and manually capture for every CC transaction that comes in. Is that correct? Can it auto-capture?

Also, can you post screenshots of the front end and what it looks like to the end user?

thanks
patrick

**Comment by JAllison4u** [comment]
No you don't have to manually capture each transaction. 
The "Sale" transaction type is as an Auth and Capture transaction, so it is immediately captured.

**Comment by pmsteil** [comment]
Excellent, thanks!
