### ISSUE TITLE
Tested on Magento 2.4.1-p1?

### ISSUE THREAD

**Issue by pmsteil** [PayFabric/Magento-Plugin#3]
Hello, the readme states this plugin is compatible with Magento 2.3 or later.

Has it been tested on 2.4.1-p1 or any other 2.4.x version?

thanks

**Comment by JAllison4u** [comment]
Our current release was tested against Magento 2.3.0 and 2.4.0.  At each release we test against the latest Magento releases.

**Comment by pmsteil** [comment]
@JAllison4u thanks!
