### ISSUE TITLE
Issues with Magento v2.3.6-p1 at checkout

### ISSUE THREAD

**Issue by ahsan-horani-folio** [PayFabric/Magento-Plugin#4]
Hi there - We are trying to configure the PayFabric but on selection of PayFabric at checkout, the dialog dies not appear. What could be the root cause of this? However, it just redirects customer to Thank You page after "Place Order"

Any help would be highly appreciated. TIA!

**Comment by JackZhang-nodus** [comment]
Thank you for your comment. Did this happen by accident or always? Are there any errors in your Magento log or browser console? Or you can share with me your Magento website configured with PayFabric so that I can reproduce it and find out the possible reasons. Thanks!

**Comment by haiyanzhangnodus** [comment]
> Hi there - We are trying to configure the PayFabric but on selection of PayFabric at checkout, the dialog dies not appear. What could be the root cause of this? However, it just redirects customer to Thank You page after "Place Order"
> 
> Any help would be highly appreciated. TIA!

Hi, are you still able to reproduce this issue? We are not able to reproduce the issue with current info you provided. Please provide some more info like Jack mentioned in previous comments, so that we can reproduce and find the reason, Thank you.

**Comment by JackZhang-nodus** [comment]
Since there has been no response from you for a long time, please allow me to close it for better management. 
If you believe it has not been resolved, please feel free to recreate it at any time. We are always here and more than happy to assist you further.
