### ISSUE TITLE
Required JavaScript file returning 404

### ISSUE THREAD

**Issue by navarr** [PayFabric/Magento-Plugin#5]
requirejs requires this JavaScript file:

`https://www.payfabric.com/Payment/WebGate/src/output/payfabricpayments.js`

However, this is returning a 404 and I cannot find a replacement.  With this file missing, the payment method fails to render

**Comment by ShaunSharples** [comment]
Hi navarr,

Thank you for reaching out and making us aware of the issue.  This has been corrected and should be working correctly now.

Regards,

Shaun

**Comment by navarr** [comment]
Thank you.  I can confirm the extension appears to be working now.
