### ISSUE TITLE
Password must be set in Configuration every save

### ISSUE THREAD

**Issue by navarr** [PayFabric/Magento-Plugin#6]
**Pre-Requisites**

* Magento 2.4.5-p1
* PayFabric should already be configured

**Recreation Steps**

* Go to Stores > Configuration > Sales > Payment Methods
* Scroll down to PayFabric Gateway payment method
* Alter the Title and edit no other fields
* Click the "Save Config" button

**:heavy_check_mark: Expected Result**

* Configuration saves successfully

**:heavy_multiplication_x: Actual Result**

* "Something went wrong while saving this configuration: Authentication Failed."

**:question: Other Notes**

Everything is successful if you re-enter the password for PayFabric.  This error also occurs if you modify other payment methods.  This appears to be due to the exception thrown at https://github.com/PayFabric/Magento-Plugin/blob/master/PayFabric/Payment/Model/Config/Backend/Gateway.php#L67. In testing, this appeared to also prevent other payment method changes from being saved as well.

Ideally, this mechanism should likely be replaced with a test configuration button that performs an AJAX call to test the entered configuration and reports back success or failure.  Such a mechanism would also reduce calls made to PayFabric servers

**Comment by JAllison4u** [comment]
We have received your submission and will review it internally.

**Comment by drsholtes** [comment]
Yes, this is very frustrating to work with

**Comment by JAllison4u** [comment]
Thanks for bringing this to our attention, we will fix this defect in the next release, v2.1.0.
