### ISSUE TITLE
Feature: Ability for Customers to Manager their Wallet in Magento

### ISSUE THREAD

**Issue by navarr** [PayFabric/Magento-Plugin#7]
When a Customer saves a credit card to their wallet, there is no method by which they may later remove it, and no way to update it outside of checking out.

**Comment by JAllison4u** [comment]
We have received your submission and will review it internally.

**Comment by JAllison4u** [comment]
We will add a method to hide the "save for Later" in the next release.

**Comment by JAllison4u** [comment]
We are continuing to research this submission.

**Comment by JAllison4u** [comment]
The ability to manage wallets will be in the next plug-in release: v2.1.0
