### ISSUE TITLE
Guests are prompted to save Credit Card to Wallet

### ISSUE THREAD

**Issue by navarr** [PayFabric/Magento-Plugin#8]
![image](https://user-images.githubusercontent.com/145128/214081732-90a548d0-5faf-4b7d-9fa9-a9e763fd9c31.png)

Guests likely shouldn't be prompted to save card details, especially since they cannot later access them.

**Comment by JAllison4u** [comment]
We have received your submission and will review it internally.

**Comment by JAllison4u** [comment]
Thanks for bringing this to our attention, in our next release, we will add the ability to hide the "Save for Later" option

**Comment by JAllison4u** [comment]
This feature will be in in the v2.1.0 version of the plug-in.
